plugins {
    id 'com.gradleup.shadow' version '8.3.0'
    id 'java'
}

group = project.group
version = project.version

repositories {
    mavenCentral()
    maven {
        name = "papermc-repo"
        url = "https://repo.papermc.io/repository/maven-public/"
    }
    maven {
        name = "sonatype"
        url = "https://oss.sonatype.org/content/groups/public/"
    }
    maven { url = "https://repo.aikar.co/content/groups/aikar/" }
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:${paperapi}")
    compileOnly("net.kyori:adventure-text-minimessage:${minimessage}")
    compileOnly("org.projectlombok:lombok:${lombok}")
    annotationProcessor("org.projectlombok:lombok:${lombok}")
    implementation("co.aikar:acf-paper:${paperacf}")
}

shadowJar {
    relocate 'co.aikar.commands', 'org.notionsmp.notion.acf'
    relocate 'co.aikar.locales', 'org.notionsmp.notion.locales'
}

def targetJavaVersion = Integer.parseInt(project.targetJavaVersion)
java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'

    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        options.release.set(targetJavaVersion)
    }
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('paper-plugin.yml') {
        expand props
    }
}

jar.dependsOn shadowJar