name: Notion
version: ${version}
main: org.notionsmp.plugins.Notion
api-version: '1.21'
load: STARTUP
author: "Akis (discord: yeahakis)"
description: Notion all in one (Chat manager, Permission Manager, etc..)
